#!/bin/bash
set -e
rm -rf ~/tmp/tf
bazel-bin/tensorflow/tools/pip_package/build_pip_package --src ~/tmp/tf --dst ~/master_wheel/centos7/
pip install --force ~/master_wheel/tensorflow-2.1.0-cp37-cp37m-linux_x86_64.whl
